// Comprehensive emoji + icon data for IconPicker / EmojiPicker.
// No external dependencies — pure data + search helpers.

export interface EmojiEntry {
  e: string // char
  n: string // name
  k: string // keywords (space separated)
}

export interface EmojiCategory {
  id: string
  label: string
  icon: string
  emojis: EmojiEntry[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    icon: '😀',
    emojis: [
      { e: '😀', n: 'grinning face', k: 'smile happy grin' },
      { e: '😃', n: 'grinning face with big eyes', k: 'smile happy joy' },
      { e: '😄', n: 'grinning face with smiling eyes', k: 'smile happy laugh' },
      { e: '😁', n: 'beaming face', k: 'smile grin happy' },
      { e: '😆', n: 'grinning squinting face', k: 'laugh lol haha' },
      { e: '😅', n: 'grinning face with sweat', k: 'nervous laugh relief' },
      { e: '🤣', n: 'rolling on the floor laughing', k: 'lol rofl funny' },
      { e: '😂', n: 'face with tears of joy', k: 'laugh cry funny lol' },
      { e: '🙂', n: 'slightly smiling face', k: 'smile ok' },
      { e: '🙃', n: 'upside-down face', k: 'silly sarcasm' },
      { e: '😉', n: 'winking face', k: 'wink flirt' },
      { e: '😊', n: 'smiling face with smiling eyes', k: 'blush happy warm' },
      { e: '😇', n: 'smiling face with halo', k: 'angel innocent' },
      { e: '🥰', n: 'smiling face with hearts', k: 'love adore crush' },
      { e: '😍', n: 'smiling face with heart-eyes', k: 'love crush heart' },
      { e: '🤩', n: 'star-struck', k: 'wow star excited' },
      { e: '😘', n: 'face blowing a kiss', k: 'kiss love' },
      { e: '😗', n: 'kissing face', k: 'kiss' },
      { e: '😚', n: 'kissing face with closed eyes', k: 'kiss love' },
      { e: '😙', n: 'kissing face with smiling eyes', k: 'kiss' },
      { e: '🥲', n: 'smiling face with tear', k: 'cry smile emotional' },
      { e: '😋', n: 'face savoring food', k: 'yum tasty delicious' },
      { e: '😛', n: 'face with tongue', k: 'silly playful' },
      { e: '😜', n: 'winking face with tongue', k: 'silly joke crazy' },
      { e: '🤪', n: 'zany face', k: 'crazy wild silly' },
      { e: '😝', n: 'squinting face with tongue', k: 'playful' },
      { e: '🤑', n: 'money-mouth face', k: 'money rich dollar' },
      { e: '🤗', n: 'smiling face with open hands', k: 'hug embrace' },
      { e: '🤭', n: 'face with hand over mouth', k: 'giggle secret oops' },
      { e: '🤫', n: 'shushing face', k: 'quiet secret shh' },
      { e: '🤔', n: 'thinking face', k: 'think hmm consider' },
      { e: '😐', n: 'neutral face', k: 'meh neutral' },
      { e: '🙄', n: 'face with rolling eyes', k: 'annoyed sarcasm' },
      { e: '😏', n: 'smirking face', k: 'smirk sly' },
      { e: '😬', n: 'grimacing face', k: 'awkward nervous' },
      { e: '😴', n: 'sleeping face', k: 'sleep tired snore' },
      { e: '🤤', n: 'drooling face', k: 'drool hungry' },
      { e: '😪', n: 'sleepy face', k: 'tired sleep' },
      { e: '😷', n: 'face with medical mask', k: 'sick ill covid mask' },
      { e: '🤒', n: 'face with thermometer', k: 'sick fever ill' },
      { e: '🤕', n: 'face with head-bandage', k: 'hurt injured' },
      { e: '🤢', n: 'nauseated face', k: 'sick vomit gross' },
      { e: '🤮', n: 'face vomiting', k: 'sick puke' },
      { e: '🤧', n: 'sneezing face', k: 'sneeze sick' },
      { e: '🥵', n: 'hot face', k: 'hot heat sweating' },
      { e: '🥶', n: 'cold face', k: 'cold freeze ice' },
      { e: '🥴', n: 'woozy face', k: 'dizzy drunk' },
      { e: '😵', n: 'face with crossed-out eyes', k: 'dizzy dead knockout' },
      { e: '🤯', n: 'exploding head', k: 'mind blown wow' },
      { e: '🤠', n: 'cowboy hat face', k: 'cowboy western' },
      { e: '🥳', n: 'partying face', k: 'party celebrate birthday' },
      { e: '🥸', n: 'disguised face', k: 'disguise glasses' },
      { e: '😎', n: 'smiling face with sunglasses', k: 'cool sunglasses' },
      { e: '🤓', n: 'nerd face', k: 'nerd geek glasses' },
      { e: '🧐', n: 'face with monocle', k: 'fancy inspect' },
      { e: '😕', n: 'confused face', k: 'confused unsure' },
      { e: '😟', n: 'worried face', k: 'worried anxious' },
      { e: '🙁', n: 'slightly frowning face', k: 'sad frown' },
      { e: '☹️', n: 'frowning face', k: 'sad' },
      { e: '😮', n: 'face with open mouth', k: 'surprised wow' },
      { e: '😯', n: 'hushed face', k: 'surprised' },
      { e: '😲', n: 'astonished face', k: 'shocked wow' },
      { e: '😳', n: 'flushed face', k: 'blush embarrassed' },
      { e: '🥺', n: 'pleading face', k: 'puppy eyes please' },
      { e: '😢', n: 'crying face', k: 'cry sad tear' },
      { e: '😭', n: 'loudly crying face', k: 'cry sob tear' },
      { e: '😤', n: 'face with steam from nose', k: 'angry huff' },
      { e: '😡', n: 'pouting face', k: 'angry rage red' },
      { e: '😠', n: 'angry face', k: 'angry mad' },
      { e: '🤬', n: 'face with symbols on mouth', k: 'swear curse' },
      { e: '😈', n: 'smiling face with horns', k: 'devil evil' },
      { e: '👿', n: 'angry face with horns', k: 'devil evil imp' },
      { e: '💀', n: 'skull', k: 'dead skull death' },
      { e: '☠️', n: 'skull and crossbones', k: 'danger poison pirate' },
      { e: '💩', n: 'pile of poo', k: 'poop funny' },
      { e: '🤡', n: 'clown face', k: 'clown funny' },
      { e: '👹', n: 'ogre', k: 'monster devil' },
      { e: '👺', n: 'goblin', k: 'monster' },
      { e: '👻', n: 'ghost', k: 'ghost halloween spooky' },
      { e: '👽', n: 'alien', k: 'alien ufo space' },
      { e: '👾', n: 'alien monster', k: 'game arcade invader' },
      { e: '🤖', n: 'robot', k: 'robot bot ai' },
      { e: '😺', n: 'grinning cat', k: 'cat happy' },
      { e: '😸', n: 'grinning cat with smiling eyes', k: 'cat happy' },
      { e: '😹', n: 'cat with tears of joy', k: 'cat laugh' },
      { e: '😻', n: 'smiling cat with heart-eyes', k: 'cat love' },
      { e: '😼', n: 'cat with wry smile', k: 'cat smirk' },
      { e: '😽', n: 'kissing cat', k: 'cat kiss' },
      { e: '🙀', n: 'weary cat', k: 'cat shocked' },
      { e: '😿', n: 'crying cat', k: 'cat sad cry' },
      { e: '😾', n: 'pouting cat', k: 'cat angry' },
    ],
  },
  {
    id: 'people',
    label: 'People',
    icon: '👋',
    emojis: [
      { e: '👋', n: 'waving hand', k: 'wave hello hi goodbye' },
      { e: '🤚', n: 'raised back of hand', k: 'hand stop' },
      { e: '🖐️', n: 'hand with fingers splayed', k: 'hand five' },
      { e: '✋', n: 'raised hand', k: 'hand stop high five' },
      { e: '🖖', n: 'vulcan salute', k: 'spock star trek' },
      { e: '👌', n: 'OK hand', k: 'ok perfect' },
      { e: '🤌', n: 'pinched fingers', k: 'italian chef kiss' },
      { e: '✌️', n: 'victory hand', k: 'peace victory' },
      { e: '🤞', n: 'crossed fingers', k: 'luck hope' },
      { e: '🤟', n: 'love-you gesture', k: 'rock love' },
      { e: '🤘', n: 'sign of the horns', k: 'rock metal' },
      { e: '🤙', n: 'call me hand', k: 'phone call shaka' },
      { e: '👈', n: 'backhand index pointing left', k: 'point left' },
      { e: '👉', n: 'backhand index pointing right', k: 'point right' },
      { e: '👆', n: 'backhand index pointing up', k: 'point up' },
      { e: '🖕', n: 'middle finger', k: 'rude' },
      { e: '👇', n: 'backhand index pointing down', k: 'point down' },
      { e: '☝️', n: 'index pointing up', k: 'point one' },
      { e: '👍', n: 'thumbs up', k: 'like approve yes great' },
      { e: '👎', n: 'thumbs down', k: 'dislike no bad' },
      { e: '✊', n: 'raised fist', k: 'fist power' },
      { e: '👊', n: 'oncoming fist', k: 'punch fist bump' },
      { e: '🤛', n: 'left-facing fist', k: 'fist bump' },
      { e: '🤜', n: 'right-facing fist', k: 'fist bump' },
      { e: '👏', n: 'clapping hands', k: 'clap applause bravo' },
      { e: '🙌', n: 'raising hands', k: 'hooray celebrate praise' },
      { e: '👐', n: 'open hands', k: 'open hug' },
      { e: '🤲', n: 'palms up together', k: 'pray ask' },
      { e: '🤝', n: 'handshake', k: 'deal agree shake' },
      { e: '🙏', n: 'folded hands', k: 'pray please thanks namaste' },
      { e: '✍️', n: 'writing hand', k: 'write note' },
      { e: '💅', n: 'nail polish', k: 'nails beauty' },
      { e: '🤳', n: 'selfie', k: 'selfie phone photo' },
      { e: '💪', n: 'flexed biceps', k: 'strong muscle gym' },
      { e: '🦾', n: 'mechanical arm', k: 'robot prosthetic' },
      { e: '🦿', n: 'mechanical leg', k: 'robot prosthetic' },
      { e: '🦵', n: 'leg', k: 'leg kick' },
      { e: '🦶', n: 'foot', k: 'foot kick' },
      { e: '👂', n: 'ear', k: 'ear listen hear' },
      { e: '🦻', n: 'ear with hearing aid', k: 'deaf hear' },
      { e: '👃', n: 'nose', k: 'nose smell' },
      { e: '🧠', n: 'brain', k: 'brain smart think' },
      { e: '🫀', n: 'anatomical heart', k: 'heart organ' },
      { e: '🫁', n: 'lungs', k: 'lungs breathe' },
      { e: '🦷', n: 'tooth', k: 'tooth dentist' },
      { e: '🦴', n: 'bone', k: 'bone skeleton' },
      { e: '👀', n: 'eyes', k: 'eyes look watch' },
      { e: '👁️', n: 'eye', k: 'eye look' },
      { e: '👶', n: 'baby', k: 'baby newborn' },
      { e: '🧒', n: 'child', k: 'child kid' },
      { e: '👦', n: 'boy', k: 'boy kid' },
      { e: '👧', n: 'girl', k: 'girl kid' },
      { e: '🧑', n: 'person', k: 'person adult' },
      { e: '👨', n: 'man', k: 'man' },
      { e: '👩', n: 'woman', k: 'woman' },
      { e: '🧓', n: 'older person', k: 'elderly grandparent' },
      { e: '👴', n: 'old man', k: 'grandpa elderly' },
      { e: '👵', n: 'old woman', k: 'grandma elderly' },
      { e: '🙍', n: 'person frowning', k: 'sad frown' },
      { e: '🙎', n: 'person pouting', k: 'pout' },
      { e: '🙅', n: 'person gesturing NO', k: 'no stop' },
      { e: '🙆', n: 'person gesturing OK', k: 'ok' },
      { e: '💁', n: 'person tipping hand', k: 'information help' },
      { e: '🙋', n: 'person raising hand', k: 'raise hand question' },
      { e: '🧏', n: 'deaf person', k: 'deaf sign' },
      { e: '🙇', n: 'person bowing', k: 'bow sorry respect' },
      { e: '🤦', n: 'person facepalming', k: 'facepalm fail' },
      { e: '🤷', n: 'person shrugging', k: 'shrug idk' },
      { e: '🧑‍💻', n: 'technologist', k: 'coder developer laptop code' },
      { e: '🧑‍🎨', n: 'artist', k: 'art paint' },
      { e: '🧑‍🚀', n: 'astronaut', k: 'space rocket' },
      { e: '🧑‍🍳', n: 'cook', k: 'chef cook food' },
      { e: '🧑‍🏫', n: 'teacher', k: 'teacher school' },
      { e: '🧑‍⚕️', n: 'health worker', k: 'doctor nurse' },
      { e: '🧑‍🌾', n: 'farmer', k: 'farm' },
      { e: '🧑‍🎓', n: 'student', k: 'graduate student' },
      { e: '🧑‍💼', n: 'office worker', k: 'office work' },
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    icon: '🌿',
    emojis: [
      { e: '🐶', n: 'dog face', k: 'dog puppy pet' },
      { e: '🐱', n: 'cat face', k: 'cat kitten pet' },
      { e: '🐭', n: 'mouse face', k: 'mouse' },
      { e: '🐹', n: 'hamster', k: 'hamster pet' },
      { e: '🐰', n: 'rabbit face', k: 'bunny rabbit' },
      { e: '🦊', n: 'fox', k: 'fox' },
      { e: '🐻', n: 'bear', k: 'bear teddy' },
      { e: '🐼', n: 'panda', k: 'panda' },
      { e: '🐨', n: 'koala', k: 'koala' },
      { e: '🐯', n: 'tiger face', k: 'tiger' },
      { e: '🦁', n: 'lion', k: 'lion king' },
      { e: '🐮', n: 'cow face', k: 'cow' },
      { e: '🐷', n: 'pig face', k: 'pig' },
      { e: '🐸', n: 'frog', k: 'frog toad' },
      { e: '🐵', n: 'monkey face', k: 'monkey' },
      { e: '🙈', n: 'see-no-evil monkey', k: 'monkey blind' },
      { e: '🙉', n: 'hear-no-evil monkey', k: 'monkey deaf' },
      { e: '🙊', n: 'speak-no-evil monkey', k: 'monkey silent' },
      { e: '🐒', n: 'monkey', k: 'monkey' },
      { e: '🐔', n: 'chicken', k: 'chicken hen' },
      { e: '🐧', n: 'penguin', k: 'penguin' },
      { e: '🐦', n: 'bird', k: 'bird' },
      { e: '🐤', n: 'baby chick', k: 'chick baby' },
      { e: '🦄', n: 'unicorn', k: 'unicorn magic' },
      { e: '🐝', n: 'honeybee', k: 'bee honey' },
      { e: '🦋', n: 'butterfly', k: 'butterfly' },
      { e: '🐌', n: 'snail', k: 'snail slow' },
      { e: '🐞', n: 'lady beetle', k: 'ladybug bug' },
      { e: '🐜', n: 'ant', k: 'ant' },
      { e: '🦟', n: 'mosquito', k: 'mosquito bite' },
      { e: '🦗', n: 'cricket', k: 'cricket' },
      { e: '🌵', n: 'cactus', k: 'cactus desert' },
      { e: '🎄', n: 'christmas tree', k: 'christmas tree holiday' },
      { e: '🌲', n: 'evergreen tree', k: 'tree pine' },
      { e: '🌳', n: 'deciduous tree', k: 'tree' },
      { e: '🌴', n: 'palm tree', k: 'palm beach tropical' },
      { e: '🌱', n: 'seedling', k: 'plant grow seedling' },
      { e: '🌿', n: 'herb', k: 'herb leaf plant' },
      { e: '☘️', n: 'shamrock', k: 'clover luck irish' },
      { e: '🍀', n: 'four leaf clover', k: 'luck clover' },
      { e: '🍁', n: 'maple leaf', k: 'leaf autumn fall' },
      { e: '🍂', n: 'fallen leaf', k: 'leaf autumn' },
      { e: '🍃', n: 'leaf fluttering in wind', k: 'leaf wind' },
      { e: '🌷', n: 'tulip', k: 'flower tulip' },
      { e: '🌹', n: 'rose', k: 'rose flower love' },
      { e: '🌻', n: 'sunflower', k: 'sunflower' },
      { e: '🌸', n: 'cherry blossom', k: 'flower blossom sakura' },
      { e: '💐', n: 'bouquet', k: 'flowers bouquet' },
      { e: '🍄', n: 'mushroom', k: 'mushroom' },
      { e: '🌍', n: 'globe showing Europe-Africa', k: 'earth globe world' },
      { e: '🌙', n: 'crescent moon', k: 'moon night' },
      { e: '⭐', n: 'star', k: 'star favorite' },
      { e: '🌟', n: 'glowing star', k: 'star glow sparkle' },
      { e: '✨', n: 'sparkles', k: 'sparkle magic new ai' },
      { e: '⚡', n: 'high voltage', k: 'lightning fast zap' },
      { e: '🔥', n: 'fire', k: 'fire hot flame lit' },
      { e: '🌈', n: 'rainbow', k: 'rainbow pride' },
      { e: '☀️', n: 'sun', k: 'sun sunny weather' },
      { e: '🌊', n: 'water wave', k: 'wave ocean surf' },
      { e: '❄️', n: 'snowflake', k: 'snow winter cold' },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    icon: '🍎',
    emojis: [
      { e: '🍎', n: 'red apple', k: 'apple fruit red' },
      { e: '🍐', n: 'pear', k: 'pear fruit' },
      { e: '🍊', n: 'tangerine', k: 'orange citrus' },
      { e: '🍋', n: 'lemon', k: 'lemon citrus' },
      { e: '🍌', n: 'banana', k: 'banana fruit' },
      { e: '🍉', n: 'watermelon', k: 'watermelon fruit' },
      { e: '🍇', n: 'grapes', k: 'grapes fruit wine' },
      { e: '🍓', n: 'strawberry', k: 'strawberry berry' },
      { e: '🫐', n: 'blueberries', k: 'blueberry berry' },
      { e: '🍈', n: 'melon', k: 'melon cantaloupe' },
      { e: '🍒', n: 'cherries', k: 'cherry' },
      { e: '🍑', n: 'peach', k: 'peach fruit' },
      { e: '🥭', n: 'mango', k: 'mango fruit' },
      { e: '🍍', n: 'pineapple', k: 'pineapple tropical' },
      { e: '🥥', n: 'coconut', k: 'coconut tropical' },
      { e: '🥝', n: 'kiwi fruit', k: 'kiwi' },
      { e: '🍅', n: 'tomato', k: 'tomato vegetable' },
      { e: '🥑', n: 'avocado', k: 'avocado' },
      { e: '🍆', n: 'eggplant', k: 'eggplant aubergine' },
      { e: '🥔', n: 'potato', k: 'potato' },
      { e: '🥕', n: 'carrot', k: 'carrot vegetable' },
      { e: '🌽', n: 'ear of corn', k: 'corn' },
      { e: '🌶️', n: 'hot pepper', k: 'spicy chili hot' },
      { e: '🥒', n: 'cucumber', k: 'cucumber pickle' },
      { e: '🥬', n: 'leafy green', k: 'lettuce salad kale' },
      { e: '🥦', n: 'broccoli', k: 'broccoli vegetable' },
      { e: '🍕', n: 'pizza', k: 'pizza slice' },
      { e: '🍔', n: 'hamburger', k: 'burger hamburger' },
      { e: '🍟', n: 'french fries', k: 'fries chips' },
      { e: '🌭', n: 'hot dog', k: 'hotdog' },
      { e: '🍿', n: 'popcorn', k: 'popcorn movie snack' },
      { e: '🥓', n: 'bacon', k: 'bacon breakfast' },
      { e: '🥚', n: 'egg', k: 'egg breakfast' },
      { e: '🍳', n: 'cooking', k: 'fried egg breakfast' },
      { e: '🧇', n: 'waffle', k: 'waffle breakfast' },
      { e: '🥞', n: 'pancakes', k: 'pancakes breakfast' },
      { e: '🧈', n: 'butter', k: 'butter' },
      { e: '🍞', n: 'bread', k: 'bread toast' },
      { e: '🥐', n: 'croissant', k: 'croissant french breakfast' },
      { e: '🧀', n: 'cheese wedge', k: 'cheese' },
      { e: '🍗', n: 'poultry leg', k: 'chicken leg meat' },
      { e: '🍖', n: 'meat on bone', k: 'meat bbq' },
      { e: '🍣', n: 'sushi', k: 'sushi japanese' },
      { e: '🍜', n: 'steaming bowl', k: 'ramen noodles soup' },
      { e: '🍝', n: 'spaghetti', k: 'pasta spaghetti' },
      { e: '🍰', n: 'shortcake', k: 'cake dessert' },
      { e: '🎂', n: 'birthday cake', k: 'birthday cake celebrate' },
      { e: '🧁', n: 'cupcake', k: 'cupcake dessert' },
      { e: '🍩', n: 'doughnut', k: 'donut sweet' },
      { e: '🍪', n: 'cookie', k: 'cookie biscuit' },
      { e: '🍫', n: 'chocolate bar', k: 'chocolate sweet' },
      { e: '🍯', n: 'honey pot', k: 'honey sweet' },
      { e: '☕', n: 'hot beverage', k: 'coffee tea hot' },
      { e: '🍵', n: 'teacup without handle', k: 'tea matcha' },
      { e: '🧋', n: 'bubble tea', k: 'boba bubble tea' },
      { e: '🍺', n: 'beer mug', k: 'beer drink' },
      { e: '🍷', n: 'wine glass', k: 'wine drink' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    icon: '✈️',
    emojis: [
      { e: '🚗', n: 'automobile', k: 'car drive' },
      { e: '🚕', n: 'taxi', k: 'taxi cab' },
      { e: '🚙', n: 'sport utility vehicle', k: 'suv car' },
      { e: '🚌', n: 'bus', k: 'bus' },
      { e: '🚎', n: 'trolleybus', k: 'bus tram' },
      { e: '🏎️', n: 'racing car', k: 'race f1 fast' },
      { e: '🚓', n: 'police car', k: 'police' },
      { e: '🚑', n: 'ambulance', k: 'ambulance emergency' },
      { e: '🚒', n: 'fire engine', k: 'fire truck' },
      { e: '🚐', n: 'minibus', k: 'van bus' },
      { e: '🛻', n: 'pickup truck', k: 'truck pickup' },
      { e: '🚚', n: 'delivery truck', k: 'truck delivery' },
      { e: '🚛', n: 'articulated lorry', k: 'truck semi' },
      { e: '🚜', n: 'tractor', k: 'tractor farm' },
      { e: '🚲', n: 'bicycle', k: 'bike bicycle cycling' },
      { e: '🛵', n: 'motor scooter', k: 'scooter vespa' },
      { e: '🏍️', n: 'motorcycle', k: 'motorcycle bike' },
      { e: '✈️', n: 'airplane', k: 'plane flight travel' },
      { e: '🛫', n: 'airplane departure', k: 'flight takeoff travel' },
      { e: '🛬', n: 'airplane arrival', k: 'flight landing travel' },
      { e: '🚀', n: 'rocket', k: 'rocket space launch startup' },
      { e: '🛸', n: 'flying saucer', k: 'ufo alien space' },
      { e: '🚁', n: 'helicopter', k: 'helicopter' },
      { e: '⛵', n: 'sailboat', k: 'sail boat' },
      { e: '🚤', n: 'speedboat', k: 'boat speed' },
      { e: '🗺️', n: 'world map', k: 'map world travel' },
      { e: '🗿', n: 'moai', k: 'statue easter island' },
      { e: '🗽', n: 'statue of liberty', k: 'liberty nyc new york' },
      { e: '🗼', n: 'tokyo tower', k: 'tokyo tower' },
      { e: '🏰', n: 'castle', k: 'castle medieval' },
      { e: '🏯', n: 'japanese castle', k: 'castle japan' },
      { e: '🏟️', n: 'stadium', k: 'stadium sports' },
      { e: '🎡', n: 'ferris wheel', k: 'ferris carnival' },
      { e: '🎢', n: 'roller coaster', k: 'coaster amusement' },
      { e: '⛺', n: 'tent', k: 'camping tent' },
      { e: '🏕️', n: 'camping', k: 'camping tent outdoors' },
      { e: '🏖️', n: 'beach with umbrella', k: 'beach vacation' },
      { e: '🏝️', n: 'desert island', k: 'island tropical' },
      { e: '🏔️', n: 'snow-capped mountain', k: 'mountain snow' },
      { e: '⛰️', n: 'mountain', k: 'mountain hike' },
      { e: '🌋', n: 'volcano', k: 'volcano lava' },
      { e: '🗻', n: 'mount fuji', k: 'fuji mountain japan' },
      { e: '🏠', n: 'house', k: 'house home' },
      { e: '🏡', n: 'house with garden', k: 'house garden home' },
      { e: '🏢', n: 'office building', k: 'office building work' },
      { e: '🏥', n: 'hospital', k: 'hospital doctor' },
      { e: '🏦', n: 'bank', k: 'bank money' },
      { e: '🏨', n: 'hotel', k: 'hotel travel' },
      { e: '🏪', n: 'convenience store', k: 'store shop' },
      { e: '🏫', n: 'school', k: 'school education' },
    ],
  },
  {
    id: 'activity',
    label: 'Activity',
    icon: '⚽',
    emojis: [
      { e: '⚽', n: 'soccer ball', k: 'soccer football sport' },
      { e: '🏀', n: 'basketball', k: 'basketball sport' },
      { e: '🏈', n: 'american football', k: 'football nfl sport' },
      { e: '⚾', n: 'baseball', k: 'baseball sport' },
      { e: '🥎', n: 'softball', k: 'softball sport' },
      { e: '🎾', n: 'tennis', k: 'tennis sport' },
      { e: '🏐', n: 'volleyball', k: 'volleyball sport' },
      { e: '🏉', n: 'rugby football', k: 'rugby sport' },
      { e: '🥏', n: 'flying disc', k: 'frisbee disc' },
      { e: '🎱', n: 'pool 8 ball', k: 'pool billiards 8ball' },
      { e: '🏓', n: 'ping pong', k: 'table tennis ping pong' },
      { e: '🏸', n: 'badminton', k: 'badminton shuttle' },
      { e: '🏒', n: 'ice hockey', k: 'hockey ice' },
      { e: '🏑', n: 'field hockey', k: 'hockey field' },
      { e: '🥍', n: 'lacrosse', k: 'lacrosse' },
      { e: '🏏', n: 'cricket game', k: 'cricket sport' },
      { e: '🪃', n: 'boomerang', k: 'boomerang' },
      { e: '🥅', n: 'goal net', k: 'goal net soccer' },
      { e: '⛳', n: 'flag in hole', k: 'golf' },
      { e: '🪁', n: 'kite', k: 'kite fly' },
      { e: '🎣', n: 'fishing pole', k: 'fishing fish' },
      { e: '🤿', n: 'diving mask', k: 'dive snorkel' },
      { e: '🥊', n: 'boxing glove', k: 'boxing fight' },
      { e: '🥋', n: 'martial arts uniform', k: 'karate judo' },
      { e: '🎽', n: 'running shirt', k: 'run marathon sport' },
      { e: '🛹', n: 'skateboard', k: 'skateboard skate' },
      { e: '🛷', n: 'sled', k: 'sled snow' },
      { e: '⛸️', n: 'ice skate', k: 'skate ice' },
      { e: '🥌', n: 'curling stone', k: 'curling' },
      { e: '🎿', n: 'skis', k: 'ski snow' },
      { e: '⛷️', n: 'skier', k: 'ski skier' },
      { e: '🏂', n: 'snowboarder', k: 'snowboard' },
      { e: '🏋️', n: 'person lifting weights', k: 'gym lift weights' },
      { e: '🤼', n: 'people wrestling', k: 'wrestling' },
      { e: '🤸', n: 'person cartwheeling', k: 'gymnastics cartwheel' },
      { e: '⛹️', n: 'person bouncing ball', k: 'basketball' },
      { e: '🤺', n: 'person fencing', k: 'fencing sword' },
      { e: '🏇', n: 'horse racing', k: 'horse race' },
      { e: '🧘', n: 'person in lotus position', k: 'yoga meditate zen' },
      { e: '🏄', n: 'person surfing', k: 'surf surfboard wave' },
      { e: '🏊', n: 'person swimming', k: 'swim pool' },
      { e: '🤽', n: 'person playing water polo', k: 'water polo' },
      { e: '🚣', n: 'person rowing boat', k: 'row boat canoe' },
      { e: '🧗', n: 'person climbing', k: 'climb boulder' },
      { e: '🚴', n: 'person biking', k: 'bike cycling' },
      { e: '🚵', n: 'person mountain biking', k: 'mountain bike' },
      { e: '🎮', n: 'video game', k: 'game gaming controller' },
      { e: '🕹️', n: 'joystick', k: 'game arcade joystick' },
      { e: '🎲', n: 'game die', k: 'dice random game' },
      { e: '🧩', n: 'puzzle piece', k: 'puzzle jigsaw' },
      { e: '♟️', n: 'chess pawn', k: 'chess pawn game' },
      { e: '🎯', n: 'bullseye', k: 'target dart goal' },
      { e: '🎳', n: 'bowling', k: 'bowling' },
      { e: '🎨', n: 'artist palette', k: 'art paint design' },
      { e: '🧵', n: 'thread', k: 'sew thread' },
      { e: '🪡', n: 'sewing needle', k: 'sew needle' },
      { e: '🎭', n: 'performing arts', k: 'theater drama masks' },
      { e: '👟', n: 'running shoe', k: 'shoe sneaker run' },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      { e: '💡', n: 'light bulb', k: 'idea bulb light' },
      { e: '🔦', n: 'flashlight', k: 'flashlight torch' },
      { e: '🕯️', n: 'candle', k: 'candle light' },
      { e: '🪔', n: 'diya lamp', k: 'lamp diwali light' },
      { e: '📱', n: 'mobile phone', k: 'phone iphone mobile' },
      { e: '💻', n: 'laptop', k: 'laptop computer macbook' },
      { e: '🖥️', n: 'desktop computer', k: 'desktop computer monitor' },
      { e: '🖨️', n: 'printer', k: 'printer print' },
      { e: '⌨️', n: 'keyboard', k: 'keyboard type' },
      { e: '🖱️', n: 'computer mouse', k: 'mouse click' },
      { e: '💾', n: 'floppy disk', k: 'save floppy disk' },
      { e: '💿', n: 'optical disk', k: 'cd dvd disk' },
      { e: '📷', n: 'camera', k: 'camera photo' },
      { e: '📸', n: 'camera with flash', k: 'camera photo flash' },
      { e: '📹', n: 'video camera', k: 'video camera film' },
      { e: '🎥', n: 'movie camera', k: 'movie film cinema' },
      { e: '📽️', n: 'film projector', k: 'projector film' },
      { e: '🎞️', n: 'film frames', k: 'film movie' },
      { e: '📞', n: 'telephone receiver', k: 'phone call' },
      { e: '☎️', n: 'telephone', k: 'phone landline' },
      { e: '📺', n: 'television', k: 'tv television' },
      { e: '📻', n: 'radio', k: 'radio' },
      { e: '🎙️', n: 'studio microphone', k: 'mic podcast microphone' },
      { e: '🎚️', n: 'level slider', k: 'slider volume mixer' },
      { e: '🎛️', n: 'control knobs', k: 'knobs mixer settings' },
      { e: '⏱️', n: 'stopwatch', k: 'timer stopwatch' },
      { e: '⏲️', n: 'timer clock', k: 'timer countdown' },
      { e: '⏰', n: 'alarm clock', k: 'alarm morning wake' },
      { e: '🕰️', n: 'mantelpiece clock', k: 'clock antique' },
      { e: '⌛', n: 'hourglass done', k: 'hourglass time done' },
      { e: '⏳', n: 'hourglass not done', k: 'hourglass waiting time' },
      { e: '📡', n: 'satellite antenna', k: 'satellite signal' },
      { e: '🔋', n: 'battery', k: 'battery charge power' },
      { e: '🔌', n: 'electric plug', k: 'plug power' },
      { e: '💡', n: 'light bulb', k: 'idea' },
      { e: '🔍', n: 'magnifying glass tilted left', k: 'search find zoom' },
      { e: '🔎', n: 'magnifying glass tilted right', k: 'search find' },
      { e: '🛠️', n: 'hammer and wrench', k: 'tools fix build' },
      { e: '🔧', n: 'wrench', k: 'wrench tool fix' },
      { e: '🔨', n: 'hammer', k: 'hammer build' },
      { e: '⚙️', n: 'gear', k: 'settings gear cog' },
      { e: '🧰', n: 'toolbox', k: 'tools toolbox' },
      { e: '🧲', n: 'magnet', k: 'magnet attract' },
      { e: '🪜', n: 'ladder', k: 'ladder climb' },
      { e: '⚗️', n: 'alembic', k: 'science chemistry' },
      { e: '🧪', n: 'test tube', k: 'science lab experiment' },
      { e: '🧫', n: 'petri dish', k: 'science biology' },
      { e: '🔬', n: 'microscope', k: 'science microscope' },
      { e: '🔭', n: 'telescope', k: 'space telescope stars' },
      { e: '📚', n: 'books', k: 'books library study' },
      { e: '📖', n: 'open book', k: 'book read open' },
      { e: '📝', n: 'memo', k: 'memo note write pencil' },
      { e: '✏️', n: 'pencil', k: 'pencil edit write' },
      { e: '🖊️', n: 'pen', k: 'pen write' },
      { e: '🖌️', n: 'paintbrush', k: 'paint brush art' },
      { e: '🖍️', n: 'crayon', k: 'crayon color' },
      { e: '📎', n: 'paperclip', k: 'clip attach' },
      { e: '🖇️', n: 'linked paperclips', k: 'clips attach' },
      { e: '📐', n: 'triangular ruler', k: 'ruler design' },
      { e: '📏', n: 'straight ruler', k: 'ruler measure' },
      { e: '📌', n: 'pushpin', k: 'pin pushpin' },
      { e: '📍', n: 'round pushpin', k: 'pin location map' },
      { e: '✂️', n: 'scissors', k: 'scissors cut' },
      { e: '🗃️', n: 'card file box', k: 'box archive files' },
      { e: '🗂️', n: 'card index dividers', k: 'index dividers organize' },
      { e: '📁', n: 'file folder', k: 'folder files' },
      { e: '📂', n: 'open file folder', k: 'folder open' },
      { e: '🗞️', n: 'rolled-up newspaper', k: 'news newspaper' },
      { e: '📰', n: 'newspaper', k: 'news paper' },
      { e: '💰', n: 'money bag', k: 'money bag dollar' },
      { e: '💳', n: 'credit card', k: 'card credit payment' },
      { e: '💎', n: 'gem stone', k: 'diamond gem precious' },
      { e: '🎁', n: 'wrapped gift', k: 'gift present birthday' },
      { e: '🏆', n: 'trophy', k: 'trophy win award' },
      { e: '🥇', n: '1st place medal', k: 'gold medal first win' },
      { e: '🎖️', n: 'military medal', k: 'medal award' },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emojis: [
      { e: '❤️', n: 'red heart', k: 'heart love red' },
      { e: '🧡', n: 'orange heart', k: 'heart orange love' },
      { e: '💛', n: 'yellow heart', k: 'heart yellow love' },
      { e: '💚', n: 'green heart', k: 'heart green love' },
      { e: '💙', n: 'blue heart', k: 'heart blue love' },
      { e: '💜', n: 'purple heart', k: 'heart purple love' },
      { e: '🖤', n: 'black heart', k: 'heart black' },
      { e: '🤍', n: 'white heart', k: 'heart white' },
      { e: '🤎', n: 'brown heart', k: 'heart brown' },
      { e: '💔', n: 'broken heart', k: 'heartbreak sad breakup' },
      { e: '❣️', n: 'heart exclamation', k: 'heart love' },
      { e: '💕', n: 'two hearts', k: 'hearts love' },
      { e: '💞', n: 'revolving hearts', k: 'hearts love' },
      { e: '💓', n: 'beating heart', k: 'heart beating love' },
      { e: '💗', n: 'growing heart', k: 'heart grow love' },
      { e: '💖', n: 'sparkling heart', k: 'heart sparkle love' },
      { e: '💘', n: 'heart with arrow', k: 'cupid love arrow' },
      { e: '💝', n: 'heart with ribbon', k: 'heart gift valentine' },
      { e: '💟', n: 'heart decoration', k: 'heart' },
      { e: '☮️', n: 'peace symbol', k: 'peace' },
      { e: '✝️', n: 'latin cross', k: 'cross christian' },
      { e: '☪️', n: 'star and crescent', k: 'islam muslim' },
      { e: '🕉️', n: 'om', k: 'om hindu' },
      { e: '☸️', n: 'wheel of dharma', k: 'buddhist dharma' },
      { e: '✡️', n: 'star of david', k: 'jewish star' },
      { e: '🔯', n: 'dotted six-pointed star', k: 'star fortune' },
      { e: '🕎', n: 'menorah', k: 'hanukkah menorah' },
      { e: '☯️', n: 'yin yang', k: 'yin yang balance' },
      { e: '☦️', n: 'orthodox cross', k: 'orthodox cross' },
      { e: '🛐', n: 'place of worship', k: 'worship pray' },
      { e: '⛎', n: 'ophiuchus', k: 'zodiac ophiuchus' },
      { e: '♈', n: 'aries', k: 'zodiac aries ram' },
      { e: '♉', n: 'taurus', k: 'zodiac taurus bull' },
      { e: '♊', n: 'gemini', k: 'zodiac gemini twins' },
      { e: '♋', n: 'cancer', k: 'zodiac cancer crab' },
      { e: '♌', n: 'leo', k: 'zodiac leo lion' },
      { e: '♍', n: 'virgo', k: 'zodiac virgo' },
      { e: '♎', n: 'libra', k: 'zodiac libra scales' },
      { e: '♏', n: 'scorpio', k: 'zodiac scorpio scorpion' },
      { e: '♐', n: 'sagittarius', k: 'zodiac sagittarius archer' },
      { e: '♑', n: 'capricorn', k: 'zodiac capricorn goat' },
      { e: '♒', n: 'aquarius', k: 'zodiac aquarius water' },
      { e: '♓', n: 'pisces', k: 'zodiac pisces fish' },
      { e: '✅', n: 'check mark button', k: 'check done todo complete' },
      { e: '☑️', n: 'check box with check', k: 'check checkbox todo done' },
      { e: '✔️', n: 'check mark', k: 'check correct' },
      { e: '❌', n: 'cross mark', k: 'cross x no delete' },
      { e: '❎', n: 'cross mark button', k: 'x cross no' },
      { e: '➕', n: 'plus', k: 'plus add new' },
      { e: '➖', n: 'minus', k: 'minus subtract remove' },
      { e: '➗', n: 'divide', k: 'divide math' },
      { e: '✖️', n: 'multiply', k: 'multiply x math' },
      { e: '♾️', n: 'infinity', k: 'infinity endless' },
      { e: '‼️', n: 'double exclamation mark', k: 'important urgent !!' },
      { e: '⁉️', n: 'exclamation question mark', k: 'confused !?' },
      { e: '❓', n: 'red question mark', k: 'question help ?' },
      { e: '❔', n: 'white question mark', k: 'question ?' },
      { e: '❕', n: 'white exclamation mark', k: 'exclamation !' },
      { e: '❗', n: 'red exclamation mark', k: 'alert important !' },
      { e: '〰️', n: 'wavy dash', k: 'dash wavy' },
      { e: '💱', n: 'currency exchange', k: 'money currency exchange' },
      { e: '💲', n: 'heavy dollar sign', k: 'dollar money $' },
      { e: '⚠️', n: 'warning', k: 'warning alert caution' },
      { e: '🚸', n: 'children crossing', k: 'children school crossing' },
      { e: '🔞', n: 'no one under eighteen', k: '18 adult nsfw' },
      { e: '☢️', n: 'radioactive', k: 'radioactive nuclear' },
      { e: '☣️', n: 'biohazard', k: 'biohazard danger' },
      { e: '⬆️', n: 'up arrow', k: 'arrow up' },
      { e: '↗️', n: 'up-right arrow', k: 'arrow up right' },
      { e: '➡️', n: 'right arrow', k: 'arrow right' },
      { e: '↘️', n: 'down-right arrow', k: 'arrow down right' },
      { e: '⬇️', n: 'down arrow', k: 'arrow down' },
      { e: '↙️', n: 'down-left arrow', k: 'arrow down left' },
      { e: '⬅️', n: 'left arrow', k: 'arrow left' },
      { e: '↖️', n: 'up-left arrow', k: 'arrow up left' },
      { e: '↕️', n: 'up-down arrow', k: 'arrow up down' },
      { e: '↔️', n: 'left-right arrow', k: 'arrow left right' },
      { e: '🔀', n: 'shuffle tracks button', k: 'shuffle random' },
      { e: '🔁', n: 'repeat button', k: 'repeat loop' },
      { e: '🔂', n: 'repeat single button', k: 'repeat one loop' },
      { e: '▶️', n: 'play button', k: 'play start' },
      { e: '⏩', n: 'fast-forward button', k: 'fast forward next' },
      { e: '⏭️', n: 'next track button', k: 'next skip' },
      { e: '⏯️', n: 'play or pause button', k: 'play pause' },
      { e: '◀️', n: 'reverse button', k: 'reverse back' },
      { e: '🔼', n: 'upwards button', k: 'up triangle' },
      { e: '⏫', n: 'fast up button', k: 'up double' },
      { e: '🔽', n: 'downwards button', k: 'down triangle' },
      { e: '⏬', n: 'fast down button', k: 'down double' },
      { e: '⏸️', n: 'pause button', k: 'pause' },
      { e: '⏹️', n: 'stop button', k: 'stop' },
      { e: '⏺️', n: 'record button', k: 'record rec' },
      { e: '⏏️', n: 'eject button', k: 'eject' },
      { e: '🎦', n: 'cinema', k: 'cinema movie film' },
      { e: '🔅', n: 'dim button', k: 'dim brightness low' },
      { e: '🔆', n: 'bright button', k: 'bright brightness high' },
      { e: '📶', n: 'antenna bars', k: 'signal wifi bars' },
      { e: '📳', n: 'vibration mode', k: 'vibrate phone' },
      { e: '📴', n: 'mobile phone off', k: 'phone off silent' },
      { e: '♻️', n: 'recycling symbol', k: 'recycle green' },
      { e: '🔰', n: 'japanese symbol for beginner', k: 'beginner japanese' },
      { e: '🔱', n: 'trident emblem', k: 'trident anchor' },
      { e: '⭕', n: 'hollow red circle', k: 'circle correct o' },
      { e: '🛑', n: 'stop sign', k: 'stop octagon' },
      { e: '🚦', n: 'traffic light', k: 'traffic light signal' },
      { e: '🎵', n: 'musical note', k: 'music note' },
      { e: '🎶', n: 'musical notes', k: 'music notes song' },
      { e: '💯', n: 'hundred points', k: '100 perfect score' },
      { e: '🔔', n: 'bell', k: 'bell notification ring' },
      { e: '🔕', n: 'bell with slash', k: 'mute silent notification off' },
      { e: '🧭', n: 'compass', k: 'compass navigate direction' },
      { e: '🪄', n: 'magic wand', k: 'magic wand ai' },
    ],
  },
]

// ---- helpers ----

export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis)

export function searchEmojis(query: string, limit = 120): EmojiEntry[] {
  const q = query.trim().toLowerCase()
  if (!q) return ALL_EMOJIS.slice(0, limit)
  const terms = q.split(/\s+/)
  const scored: { entry: EmojiEntry; score: number }[] = []
  for (const entry of ALL_EMOJIS) {
    const hay = `${entry.n} ${entry.k} ${entry.e}`.toLowerCase()
    let score = 0
    let matchedAll = true
    for (const t of terms) {
      if (entry.n.toLowerCase().startsWith(t)) score += 3
      else if (entry.n.toLowerCase().includes(t)) score += 2
      else if (hay.includes(t)) score += 1
      else {
        matchedAll = false
        break
      }
    }
    if (matchedAll) scored.push({ entry, score })
  }
  scored.sort((a, b) => b.score - a.score)
  return scored.slice(0, limit).map((s) => s.entry)
}

const RECENT_KEY = 'nexus_recent_emojis'
const RECENT_MAX = 24

export function getRecentEmojis(): string[] {
  try {
    const raw = localStorage.getItem(RECENT_KEY)
    if (!raw) return []
    const arr = JSON.parse(raw)
    return Array.isArray(arr) ? arr.filter((x) => typeof x === 'string').slice(0, RECENT_MAX) : []
  } catch {
    return []
  }
}

export function addRecentEmoji(emoji: string) {
  try {
    const cur = getRecentEmojis().filter((e) => e !== emoji)
    cur.unshift(emoji)
    localStorage.setItem(RECENT_KEY, JSON.stringify(cur.slice(0, RECENT_MAX)))
  } catch {
    /* ignore */
  }
}

// ---- Lucide icon catalog (names must exist in lucide-react; resolved dynamically so missing names safely fallback) ----

export interface LucideEntry {
  name: string
  label: string
  keywords: string
}

export const LUCIDE_ICONS: LucideEntry[] = [
  { name: 'Rocket', label: 'Rocket', keywords: 'rocket launch startup space fast' },
  { name: 'Star', label: 'Star', keywords: 'star favorite rating' },
  { name: 'Heart', label: 'Heart', keywords: 'heart love like' },
  { name: 'Zap', label: 'Zap', keywords: 'zap fast electric energy' },
  { name: 'Flame', label: 'Flame', keywords: 'fire flame hot trending' },
  { name: 'Sparkles', label: 'Sparkles', keywords: 'sparkles ai magic new' },
  { name: 'Target', label: 'Target', keywords: 'target goal bullseye' },
  { name: 'Flag', label: 'Flag', keywords: 'flag milestone report' },
  { name: 'Bookmark', label: 'Bookmark', keywords: 'bookmark save' },
  { name: 'Tag', label: 'Tag', keywords: 'tag label' },
  { name: 'Briefcase', label: 'Briefcase', keywords: 'work job business' },
  { name: 'GraduationCap', label: 'Graduation', keywords: 'education school graduate' },
  { name: 'BookOpen', label: 'Book', keywords: 'book read docs knowledge' },
  { name: 'NotebookPen', label: 'Notebook', keywords: 'note journal write' },
  { name: 'FileText', label: 'Document', keywords: 'doc document text page' },
  { name: 'Files', label: 'Files', keywords: 'files documents' },
  { name: 'Folder', label: 'Folder', keywords: 'folder files directory' },
  { name: 'Database', label: 'Database', keywords: 'database data table' },
  { name: 'Table', label: 'Table', keywords: 'table grid data' },
  { name: 'Kanban', label: 'Kanban', keywords: 'kanban board tasks' },
  { name: 'Calendar', label: 'Calendar', keywords: 'calendar date schedule' },
  { name: 'CalendarDays', label: 'Calendar days', keywords: 'calendar schedule planning' },
  { name: 'CheckSquare', label: 'Check', keywords: 'check todo done task' },
  { name: 'ListChecks', label: 'Checklist', keywords: 'checklist tasks todo' },
  { name: 'ListTodo', label: 'Todo list', keywords: 'todo tasks list' },
  { name: 'ClipboardList', label: 'Clipboard', keywords: 'clipboard tasks list' },
  { name: 'Inbox', label: 'Inbox', keywords: 'inbox incoming mail' },
  { name: 'Mail', label: 'Mail', keywords: 'mail email inbox' },
  { name: 'MessageSquare', label: 'Message', keywords: 'message chat comment' },
  { name: 'MessagesSquare', label: 'Messages', keywords: 'messages chat discussion' },
  { name: 'Users', label: 'Users', keywords: 'users team people' },
  { name: 'User', label: 'User', keywords: 'user person profile' },
  { name: 'Contact', label: 'Contact', keywords: 'contact address book' },
  { name: 'Settings', label: 'Settings', keywords: 'settings gear config' },
  { name: 'SlidersHorizontal', label: 'Sliders', keywords: 'settings sliders adjust' },
  { name: 'Wrench', label: 'Wrench', keywords: 'wrench tool fix' },
  { name: 'Hammer', label: 'Hammer', keywords: 'hammer build' },
  { name: 'Cog', label: 'Cog', keywords: 'cog gear settings' },
  { name: 'Code', label: 'Code', keywords: 'code developer programming' },
  { name: 'Terminal', label: 'Terminal', keywords: 'terminal cli code' },
  { name: 'Braces', label: 'Braces', keywords: 'code json braces' },
  { name: 'Bug', label: 'Bug', keywords: 'bug issue debug' },
  { name: 'GitBranch', label: 'Git branch', keywords: 'git branch version' },
  { name: 'Github', label: 'Github', keywords: 'github code repo' },
  { name: 'Globe', label: 'Globe', keywords: 'globe world web' },
  { name: 'Compass', label: 'Compass', keywords: 'compass explore navigate' },
  { name: 'Map', label: 'Map', keywords: 'map location' },
  { name: 'MapPin', label: 'Pin', keywords: 'pin location map' },
  { name: 'Home', label: 'Home', keywords: 'home house dashboard' },
  { name: 'Building', label: 'Building', keywords: 'building office company' },
  { name: 'Store', label: 'Store', keywords: 'store shop' },
  { name: 'ShoppingCart', label: 'Cart', keywords: 'cart shopping ecommerce' },
  { name: 'CreditCard', label: 'Card', keywords: 'card payment billing' },
  { name: 'Wallet', label: 'Wallet', keywords: 'wallet money' },
  { name: 'DollarSign', label: 'Dollar', keywords: 'dollar money finance' },
  { name: 'TrendingUp', label: 'Trending up', keywords: 'growth chart up analytics' },
  { name: 'BarChart3', label: 'Chart', keywords: 'chart analytics stats' },
  { name: 'PieChart', label: 'Pie chart', keywords: 'pie chart analytics' },
  { name: 'LineChart', label: 'Line chart', keywords: 'line chart growth' },
  { name: 'Presentation', label: 'Presentation', keywords: 'presentation slides pitch' },
  { name: 'Lightbulb', label: 'Idea', keywords: 'idea lightbulb think' },
  { name: 'Brain', label: 'Brain', keywords: 'brain ai smart think' },
  { name: 'Bot', label: 'Bot', keywords: 'bot ai robot' },
  { name: 'Cpu', label: 'CPU', keywords: 'cpu chip processor' },
  { name: 'Palette', label: 'Palette', keywords: 'design art color palette' },
  { name: 'Brush', label: 'Brush', keywords: 'brush paint design' },
  { name: 'PenTool', label: 'Pen tool', keywords: 'design pen vector' },
  { name: 'Figma', label: 'Figma', keywords: 'figma design' },
  { name: 'Image', label: 'Image', keywords: 'image photo picture' },
  { name: 'Camera', label: 'Camera', keywords: 'camera photo' },
  { name: 'Video', label: 'Video', keywords: 'video film' },
  { name: 'Music', label: 'Music', keywords: 'music audio song' },
  { name: 'Headphones', label: 'Headphones', keywords: 'headphones audio music' },
  { name: 'Mic', label: 'Mic', keywords: 'mic microphone voice' },
  { name: 'Bell', label: 'Bell', keywords: 'bell notification alert' },
  { name: 'AlarmClock', label: 'Alarm', keywords: 'alarm clock time' },
  { name: 'Clock', label: 'Clock', keywords: 'clock time recent' },
  { name: 'Timer', label: 'Timer', keywords: 'timer countdown stopwatch' },
  { name: 'Hourglass', label: 'Hourglass', keywords: 'hourglass waiting time' },
  { name: 'Sun', label: 'Sun', keywords: 'sun day light' },
  { name: 'Moon', label: 'Moon', keywords: 'moon night dark' },
  { name: 'Cloud', label: 'Cloud', keywords: 'cloud weather storage' },
  { name: 'CloudRain', label: 'Rain', keywords: 'rain weather cloud' },
  { name: 'Snowflake', label: 'Snow', keywords: 'snow winter cold' },
  { name: 'Leaf', label: 'Leaf', keywords: 'leaf nature green' },
  { name: 'TreePine', label: 'Tree', keywords: 'tree nature pine' },
  { name: 'Flower', label: 'Flower', keywords: 'flower nature' },
  { name: 'PawPrint', label: 'Paw', keywords: 'paw animal pet' },
  { name: 'Fish', label: 'Fish', keywords: 'fish sea' },
  { name: 'Bird', label: 'Bird', keywords: 'bird fly' },
  { name: 'Cat', label: 'Cat', keywords: 'cat pet' },
  { name: 'Dog', label: 'Dog', keywords: 'dog pet' },
  { name: 'Rabbit', label: 'Rabbit', keywords: 'rabbit bunny' },
  { name: 'Trophy', label: 'Trophy', keywords: 'trophy win award' },
  { name: 'Award', label: 'Award', keywords: 'award badge medal' },
  { name: 'Medal', label: 'Medal', keywords: 'medal award win' },
  { name: 'Crown', label: 'Crown', keywords: 'crown king premium' },
  { name: 'Gem', label: 'Gem', keywords: 'gem diamond premium' },
  { name: 'Gift', label: 'Gift', keywords: 'gift present' },
  { name: 'PartyPopper', label: 'Party', keywords: 'party celebrate popper' },
  { name: 'Cake', label: 'Cake', keywords: 'cake birthday' },
  { name: 'Coffee', label: 'Coffee', keywords: 'coffee drink cafe' },
  { name: 'Pizza', label: 'Pizza', keywords: 'pizza food' },
  { name: 'Apple', label: 'Apple', keywords: 'apple fruit food' },
  { name: 'Car', label: 'Car', keywords: 'car drive travel' },
  { name: 'Plane', label: 'Plane', keywords: 'plane flight travel' },
  { name: 'Ship', label: 'Ship', keywords: 'ship boat travel' },
  { name: 'Train', label: 'Train', keywords: 'train travel' },
  { name: 'Bike', label: 'Bike', keywords: 'bike cycling' },
  { name: 'Dumbbell', label: 'Dumbbell', keywords: 'gym fitness workout' },
  { name: 'HeartPulse', label: 'Health', keywords: 'health pulse heartbeat' },
  { name: 'Stethoscope', label: 'Medical', keywords: 'medical doctor health' },
  { name: 'Pill', label: 'Pill', keywords: 'pill medicine drug' },
  { name: 'Shield', label: 'Shield', keywords: 'shield security protect' },
  { name: 'Lock', label: 'Lock', keywords: 'lock secure private' },
  { name: 'Key', label: 'Key', keywords: 'key access password' },
  { name: 'Eye', label: 'Eye', keywords: 'eye view visible' },
  { name: 'Search', label: 'Search', keywords: 'search find' },
  { name: 'Filter', label: 'Filter', keywords: 'filter sort' },
  { name: 'Link', label: 'Link', keywords: 'link url' },
  { name: 'Paperclip', label: 'Clip', keywords: 'attach clip file' },
  { name: 'Printer', label: 'Printer', keywords: 'printer print' },
  { name: 'Download', label: 'Download', keywords: 'download save' },
  { name: 'Upload', label: 'Upload', keywords: 'upload share' },
  { name: 'Share2', label: 'Share', keywords: 'share send' },
  { name: 'Send', label: 'Send', keywords: 'send message' },
  { name: 'Archive', label: 'Archive', keywords: 'archive box' },
  { name: 'Trash2', label: 'Trash', keywords: 'trash delete remove' },
  { name: 'Pencil', label: 'Pencil', keywords: 'pencil edit write' },
  { name: 'BookMarked', label: 'Bookmark', keywords: 'bookmark docs saved' },
  { name: 'Layers', label: 'Layers', keywords: 'layers stack' },
  { name: 'Grid', label: 'Grid', keywords: 'grid layout' },
  { name: 'LayoutDashboard', label: 'Dashboard', keywords: 'dashboard layout home' },
  { name: 'LayoutTemplate', label: 'Template', keywords: 'template layout' },
  { name: 'Boxes', label: 'Boxes', keywords: 'boxes packages' },
  { name: 'Package', label: 'Package', keywords: 'package box' },
  { name: 'Gamepad2', label: 'Gamepad', keywords: 'game gaming controller' },
  { name: 'Dices', label: 'Dice', keywords: 'dice random game' },
  { name: 'Puzzle', label: 'Puzzle', keywords: 'puzzle piece' },
  { name: 'Wand2', label: 'Wand', keywords: 'wand magic ai' },
]

export function searchLucideIcons(query: string, limit = 120): LucideEntry[] {
  const q = query.trim().toLowerCase()
  if (!q) return LUCIDE_ICONS.slice(0, limit)
  const terms = q.split(/\s+/)
  const scored: { entry: LucideEntry; score: number }[] = []
  for (const entry of LUCIDE_ICONS) {
    const hay = `${entry.label} ${entry.name} ${entry.keywords}`.toLowerCase()
    let score = 0
    let ok = true
    for (const t of terms) {
      if (entry.label.toLowerCase().startsWith(t)) score += 3
      else if (entry.label.toLowerCase().includes(t)) score += 2
      else if (hay.includes(t)) score += 1
      else {
        ok = false
        break
      }
    }
    if (ok) scored.push({ entry, score })
  }
  scored.sort((a, b) => b.score - a.score)
  return scored.slice(0, limit).map((s) => s.entry)
}
